[package]
name = "axcomp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[features]
default = ["monolithic"]

monolithic = [
    "arch_boot/monolithic",
    "axfeat/monolithic",
    "paging",
    "fs",
    "multitask",
    "irq",
]

alloc = ["axfeat/alloc"]

img = ["axfeat/img"]

# Multicore
smp = ["axfeat/smp", "arch_boot/smp"]

# Floating point/SIMD
fp_simd = ["axfeat/fp_simd", "arch_boot/fp_simd"]

# Interrupts
irq = ["axfeat/irq", "arch_boot/irq"]

# Memory
paging = ["axfeat/paging"]
tls = ["axfeat/tls"]

# Multi-threading and scheduler
multitask = ["axfeat/multitask"]
sched_fifo = ["axfeat/sched_fifo"]
sched_rr = ["axfeat/sched_rr", "arch_boot/preempt"]
sched_cfs = ["axfeat/sched_cfs", "arch_boot/preempt"]

# Display
display = ["axfeat/display"]

# Bus-Pci
bus-pci = ["axfeat/bus-pci"]

# Fs
fs = ["axfeat/fs"]
fatfs = ["axfeat/fatfs"]
ext4fs = ["axfeat/ext4fs"]
myfs = ["axfeat/myfs"]
devfs = []

# Network
#net = ["axfeat/net", "linux_syscall_api/net"]

# Logging
log-level-off = ["axfeat/log-level-off"]
log-level-error = ["axfeat/log-level-error"]
log-level-warn = ["axfeat/log-level-warn"]
log-level-info = ["axfeat/log-level-info"]
log-level-debug = ["axfeat/log-level-debug"]
log-level-trace = ["axfeat/log-level-trace"]

[dependencies]
linux_syscall_api = { path = "../../api/linux_syscall_api" }
axfeat = { path = "../../api/axfeat" }
axlog = { path = "../../modules/axlog" }
arch_boot = { path = "../../crates/arch_boot" }
